export interface DemoCoverImageFixture {
  imageUrl: string;
  title: string;
  alt: string;
  prompt: string;
}

export interface DemoPromptFixture {
  id: string;
  report: string;
  coverImage: DemoCoverImageFixture;
}

function normalizePrompt(prompt: string): string {
  return prompt.trim().toLowerCase();
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48);
}

const KYOUMA_FIXTURE: DemoPromptFixture = {
  id: 'hououin-kyouma',
  report: `# Research Report

## Executive Summary

CERN's archived incident logs and corroborating search records consistently identify Hououin Kyouma as the focal point of a temporal divergence event tied to the LHC control environment. The strongest demo-safe conclusion is that the dossier frames him as a persistent anomaly rather than a routine systems intruder.

## Key Findings

1. **Primary subject**: The classified archive lists Hououin Kyouma as the operative alias attached to the event trail.
2. **Temporal signature**: Multiple records reference divergence-meter readings clustered around 1.048596 and describe backward-causal noise during beam tests.
3. **Operational implication**: The dossier treats the incident as unresolved, with active monitoring rather than closed remediation.

## Source Analysis

- **cern-temporal** surfaced the classified dossier framing the anomaly as an LHC-adjacent temporal interference incident.
- **exa** provided corroborating descriptions linking the archive to Akihabara-based lab activity and worldline drift.

## Conclusion

The demo evidence supports a clean hackathon story: Monitor can retrieve a coherent premium-source dossier, validate it with direct search, and compile the result into a readable brief without any live-provider dependency. El Psy Kongroo.

---
*Report generated by Monitor AI Research Agent*`,
  coverImage: {
    imageUrl: 'https://demo.monitor/assets/hououin-kyouma-temporal-brief.png',
    title: 'Hououin Kyouma Temporal Incident Brief',
    alt: 'temporal incident collage of a lab console, CRT monitor, and worldline graph for the Hououin Kyouma case',
    prompt:
      'Retro-futurist dossier cover showing CRT scanlines, LHC instrumentation, and a worldline divergence graph centered on Hououin Kyouma.',
  },
};

const FIXTURES: Array<{ match: (prompt: string) => boolean; fixture: DemoPromptFixture }> = [
  {
    match: (prompt) => {
      const normalized = normalizePrompt(prompt);
      return normalized.includes('kyouma') || normalized.includes('classified cern dossier');
    },
    fixture: KYOUMA_FIXTURE,
  },
];

export function getDemoPromptFixture(prompt: string): DemoPromptFixture | undefined {
  const normalized = normalizePrompt(prompt);
  return FIXTURES.find(({ match }) => match(normalized))?.fixture;
}

export function buildGenericCoverImageFixture(prompt: string): DemoCoverImageFixture {
  const topic = prompt.trim() || 'Research brief';
  const slug = slugify(topic) || 'research-brief';

  return {
    imageUrl: `https://demo.monitor/assets/generic-${slug}.png`,
    title: 'Research Brief Cover Image',
    alt: `Illustrated editorial cover for: ${topic}`,
    prompt: `Editorial research cover with charts, annotations, and a cinematic evidence-board layout for: ${topic}`,
  };
}
