import { getDemoPromptFixture } from '../demo/prompt-fixtures';

/**
 * LLM Synthesis Tool
 *
 * Calls an LLM (Anthropic Claude by default) to synthesize a research report
 * from gathered tool results. Falls back to deterministic demo output.
 */

// =============================================================================
// Types
// =============================================================================

export interface ToolResultData {
  toolId: string;
  data: unknown;
}

export interface SynthesisRequest {
  prompt: string;
  toolResults: ToolResultData[];
  taskId: string;
}

export type LLMCallFn = (systemPrompt: string, userMessage: string) => Promise<string>;

export interface LLMAdapterOptions {
  apiKey?: string;
  demoMode?: boolean;
  fallbackToDemo?: boolean;
  llmCallFn?: LLMCallFn;
  model?: string;
}

// =============================================================================
// System Prompt
// =============================================================================

const SYSTEM_PROMPT = `You are a precise research synthesis agent. Your job is to take
raw data gathered from multiple sources and synthesize it into a clear, well-structured
research report. Be factual, cite your sources, and acknowledge uncertainty where it exists.
Format the report in Markdown with clear sections: Executive Summary, Key Findings,
Source Analysis, and Conclusion. Keep it concise but comprehensive.`;

// =============================================================================
// Demo Synthesis
// =============================================================================

function demoSynthesize(request: SynthesisRequest): string {
  const fixture = getDemoPromptFixture(request.prompt);
  if (fixture) {
    return fixture.report;
  }

  const sourceList = request.toolResults.map(r => `- **${r.toolId}**`).join('\n');
  const hasResults = request.toolResults.some(r => {
    const d = r.data as any;
    return d?.results?.length > 0 || d?.findings || d?.text;
  });

  return `# Research Report

## Executive Summary

This report synthesizes findings from ${request.toolResults.length} data source(s) regarding:
> "${request.prompt}"

${hasResults ? 'Substantial relevant data was retrieved across all queried sources.' : 'Limited data was available from the queried sources.'}

## Key Findings

1. **Primary Discovery**: Analysis of available data reveals patterns consistent with the research objective.
2. **Cross-Source Validation**: Multiple independent sources corroborate the core findings.
3. **Confidence Level**: High — data from authoritative sources with strong relevance scores.

## Source Analysis

${sourceList}

Each source contributed unique perspectives, with overlapping evidence strengthening overall conclusions.

## Conclusion

The research objective has been addressed with available data. The synthesized findings provide
a coherent picture suitable for further analysis or decision-making.

---
*Report generated by Monitor AI Research Agent*
*Sources: ${request.toolResults.map(r => r.toolId).join(', ')}*`;
}

// =============================================================================
// LLM Adapter
// =============================================================================

export class LLMAdapter {
  private apiKey: string;
  private demoMode: boolean;
  private fallbackToDemo: boolean;
  private llmCallFn?: LLMCallFn;
  private model: string;

  constructor(options: LLMAdapterOptions = {}) {
    this.apiKey = options.apiKey ?? process.env['LLM_API_KEY'] ?? '';
    this.demoMode = options.demoMode ?? false;
    this.fallbackToDemo = options.fallbackToDemo ?? true;
    this.llmCallFn = options.llmCallFn;
    this.model = options.model ?? 'claude-3-haiku-20240307';
  }

  /**
   * Synthesize a research report from tool results.
   */
  async synthesize(request: SynthesisRequest): Promise<string> {
    if (this.demoMode) {
      return demoSynthesize(request);
    }

    try {
      return await this.liveSynthesize(request);
    } catch (err) {
      if (this.fallbackToDemo) {
        return demoSynthesize(request);
      }
      throw err;
    }
  }

  private async liveSynthesize(request: SynthesisRequest): Promise<string> {
    const userMessage = this.buildUserMessage(request);

    // Use injected function (for tests) or real Anthropic API
    if (this.llmCallFn) {
      return this.llmCallFn(SYSTEM_PROMPT, userMessage);
    }

    return this.callAnthropic(userMessage);
  }

  private buildUserMessage(request: SynthesisRequest): string {
    const dataStr = request.toolResults
      .map(r => `### Source: ${r.toolId}\n\`\`\`json\n${JSON.stringify(r.data, null, 2)}\n\`\`\``)
      .join('\n\n');

    return `Research objective: "${request.prompt}"\n\nGathered data:\n\n${dataStr}\n\nPlease synthesize a research report from this data.`;
  }

  private async callAnthropic(userMessage: string): Promise<string> {
    if (!this.apiKey) {
      throw new Error('LLM_API_KEY_NOT_SET');
    }

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': this.apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: this.model,
        max_tokens: 2048,
        system: SYSTEM_PROMPT,
        messages: [{ role: 'user', content: userMessage }],
      }),
    });

    if (!response.ok) {
      throw new Error(`Anthropic API error: ${response.status}`);
    }

    const body = await response.json() as {
      content: Array<{ type: string; text: string }>;
    };

    const textBlock = body.content.find(b => b.type === 'text');
    if (!textBlock) {
      throw new Error('No text in Anthropic response');
    }

    return textBlock.text;
  }
}
